
# version: '3.8'

services:
  web:
    build: "E:/POS - React - React Router - jsx - Redux/pos-backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "E:/POS - React - React Router - jsx - Redux/pos-backend/:/usr/src/pos-backend/"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRESS_DB=pos_react_reactrouter_jsx_redux

volumes:
  postgres_data:

